export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
